---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/

server:
  # 如果没有指定PORT或者SERVER_PORT,则选择任意一个可用的端口
  port: ${PORT:${SERVER_PORT:0}}   

---
spring:
  profiles: default

---
spring:
  profiles: production

---
spring:
  profiles: development

---
spring:
  profiles: test